


grafo = {
    'Aeroporto': {'MEREC', 'OLAM'},
    'Manhica': {'Xinavane', 'Matola'},
    'Palmeira': {'Xinavane', 'Matola'},
    'Xinavane': {'Manhica', 'Palmeira', 'Chokwe'},
    'Macia': {'Chokwe', 'PARMALAT'},
    'Chokwe': {'Xinavane', 'Macia', 'Lionde', 'Bilene'},
    'Lionde': {'Chokwe', 'Chicumbane', 'PARMALAT'},
    'Chibuto': {'Chaimite', 'Chicumbane', 'PARMALAT'},
    'Chaimite': {'Chibuto', 'Mabalane'},
    'Mabalane': {'Chaimite', 'Chicumbane', 'Chimoio'},
    'Chicumbane': {'Lionde', 'Chibuto', 'Mabalane', 'Xai-Xai'},
    'Xai-Xai': {'Chicumbane', 'Bilene', 'SHOPRITE'},
    'Matola': {'Manhica', 'Palmeira', 'Marracuene', 'OLAM'},
    'Bilene': {'Chokwe', 'Xai-Xai', 'Inharrime'},
    'Inharrime': {'Bilene', 'Panda', 'Magude', 'Sabie'},
    'Inhambane': {'Vilanculos', 'Massinga', 'Magude'},
    'Maxixe': {'Vilanculos', 'Panda', 'Magude'},
    'Panda': {'Inharrime', 'Maxixe', 'SHOPRITE'},
    'Vilanculos': {'Inhambane', 'Maxixe', 'Save'},
    'Massinga': {'Inhambane', 'Govuro', 'Ressano_Garcia'},
    'Govuro': {'Massinga', 'Save'},
    'Save': {'Govuro', 'Vilanculos', 'RECHEIO'},
    'Marracuene': {'Matola', 'Sabie', 'OLAM'},
    'Muxungue': {'Dondo', 'RECHEIO', 'SHOPRITE'},
    'Dondo': {'Muxungue', 'Nhamatanda', 'Sussundenga'},
    'Nhamatanda': {'Dondo', 'Manica', 'Gondola', 'SHOPRITE'},
    'Chimoio': {'Mabalane', 'Gondola', 'SHOPRITE'},
    'Gondola': {'Nhamatanda', 'Chimoio', 'SPAR'},
    'Manica': {'Nhamatanda', 'Catandica', 'Espungabera', 'SPAR'},
    'Catandica': {'Manica', 'Espungabera', 'Sussundenga'},
    'Espungabera': {'Manica', 'Catandica', 'Tica'},
    'Sussundenga': {'Dondo', 'Catandica', 'Tica'},
    'Tica': {'Espungabera', 'Sussundenga', 'Mocuba'},
    'Boane': {'Ressano_Garcia', 'Magude', 'OLAM'},
    'Mocuba': {'Tica', 'Nova_Mambone', 'Inhassoro', 'RECHEIO'},
    'Nova_Mambone': {'Mocuba', 'Inhassoro'},
    'Inhassoro': {'Mocuba', 'Nova_Mambone', 'Namaacha'},
    'Ressano_Garcia': {'Massinga', 'Boane', 'MEREC'},
    'Namaacha': {'Inhassoro', 'MEREC'},
    'Magude': {'Inharrime', 'Inhambane', 'Maxixe', 'Boane', 'Sabie'},
    'Sabie': {'Inharrime', 'Marracuene', 'Magude'},
    'MEREC': {'Aeroporto', 'Ressano_Garcia', 'Namaacha'},
    'OLAM': {'Aeroporto', 'Matola', 'Marracuene', 'Boane'},
    'PARMALAT': {'Macia', 'Lionde', 'Chibuto'},
    'RECHEIO': {'Save', 'Muxungue', 'Mocuba'},
    'SHOPRITE': {'Xai-Xai', 'Panda', 'Muxungue', 'Nhamatanda', 'Chimoio'},
    'SPAR': {'Gondola', 'Manica'}
}
